// Correct Type definitions for PeerJS

type RTCPeerConnectionConfig = any
type RTCDataChannel = any

declare namespace PeerJs {
    export type peerID = string
    export type dcID = string

    interface PeerJSOption {
        logFunction?: (...args: any[]) => void
    }

    interface DataConnection {
        removeAllListeners: () => void
        id: string
    }


    const PeerClass: {
        prototype: RTCIceServer;
        /**
         * A peer can connect to other peers and listen for connections.
         * @param id Other peers can connect to this peer using the provided ID.
         *     If no ID is given, one will be generated by the brokering server.
         * @param options for specifying details about PeerServer
         */
        new (id: string, options?: PeerJs.PeerJSOption): PeerJs.Peer;

        /**
         * A peer can connect to other peers and listen for connections.
         * @param options for specifying details about PeerServer
         */
        new (options: PeerJs.PeerJSOption): PeerJs.Peer;
    };
}